### ISSUE TITLE
Not loading on Windows CCL-32 

### ISSUE THREAD

**Issue by wnortje** [xach/buildapp#21]
When I do ```(ql:quickload "buildapp")``` I get the following error:

    The value #P"buildapp.exe" is not of the expected type SEQUENCE.
      [Condition of type TYPE-ERROR]

It looks like it is caused by this form in buildapp.lisp
```(defparameter *output-type-pathname* ....)```

I am using CCL "Version 1.10-r16196  (WindowsX8632)" on Windows XP 32b.

**Comment by xach** [comment]
What version of buildapp are you using?

**Comment by gitwn** [comment]
I used buildapp-1.5.2 / quicklisp 2014-07-14 but I updated to buildapp-1.5.4 / quicklisp 2015-05-05 and still get the same issue.

**Comment by gitwn** [comment]
It works when, in buildapp.lisp, I change this line
```(make-pathname :type #+windows #P"buildapp.exe" #-windows nil)```
to
``(make-pathname :type #+windows "buildapp.exe" #-windows nil)```

**Comment by xach** [comment]
Thanks, that's right. I have a new branch of buildapp development that fixes this, and cleans up a lot of other issues, but it's not complete yet.
